theme: jekyll-theme-time-machine
title: Welcome to our submission for the Cell and Molecular Biology groupwork project!
description: This is a game developed by all of us to guide you through the trials and tribulations a sequence of genetic code has to go to to become a protein with a specific function.
